'use strict';

/**
 * /init support: sniff a project (language, build/test/lint commands, layout)
 * and generate an AEGIS.md with real project instructions. Never overwrites an
 * existing file — the handler reports and leaves the file alone.
 *
 * Ported from aegiscodex-dev/src/init.js (ESM → CommonJS). The reference wrote
 * a CLAUDE.md; this build writes AEGIS.md and the generated document is headed
 * "# AEGIS.md" and references "AEGIS Code". The `buildClaudeMd` export is kept
 * as an alias of `buildAegisMd` so callers ported from the reference still
 * resolve.
 */

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

function readJson(p, cwd) {
  try { return JSON.parse(fs.readFileSync(path.join(cwd, p), 'utf8')); } catch { return null; }
}

function hasFile(cwd, ...names) {
  return names.some((n) => fs.existsSync(path.join(cwd, n)));
}

function gitName(cwd) {
  try {
    const remote = execSync('git config --get remote.origin.url', { encoding: 'utf8', cwd, stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    const base = remote.split('/').pop().replace(/\.git$/, '');
    if (base) return base;
  } catch {}
  try {
    const dir = cwd.split('/').filter(Boolean).pop();
    return dir || 'this project';
  } catch { return 'this project'; }
}

/** Describe a project enough to write a useful AEGIS.md. */
function sniffProject(cwd = process.cwd()) {
  const pkg = readJson('package.json', cwd);
  const out = {
    name: pkg && pkg.name ? pkg.name : gitName(cwd),
    lang: 'unknown',
    build: null,
    test: null,
    lint: null,
    dev: null,
    structure: [],
    toolchain: [],
  };

  if (pkg) {
    out.lang = 'JavaScript/TypeScript (Node.js)';
    out.toolchain.push('Node.js');
    const scripts = pkg.scripts || {};
    if (scripts.build) out.build = `npm run build`;
    if (scripts.test) out.test = `npm test`;
    if (scripts.lint) out.lint = `npm run lint`;
    if (scripts.dev || scripts.start || scripts.watch) out.dev = scripts.dev ? `npm run dev` : `npm start`;
    if (pkg.packageManager) out.toolchain.push(pkg.packageManager);
  } else if (hasFile(cwd, 'go.mod')) {
    out.lang = 'Go';
    out.toolchain.push('Go');
    out.build = 'go build ./...';
    out.test = 'go test ./...';
    out.lint = 'golangci-lint run' ;
    out.dev = 'go run .';
  } else if (hasFile(cwd, 'Cargo.toml')) {
    out.lang = 'Rust';
    out.toolchain.push('Cargo');
    out.build = 'cargo build';
    out.test = 'cargo test';
    out.lint = 'cargo clippy -- -D warnings';
    out.dev = 'cargo run';
  } else if (hasFile(cwd, 'pyproject.toml', 'setup.py', 'requirements.txt')) {
    out.lang = 'Python';
    out.toolchain.push('Python');
    out.test = hasFile(cwd, 'pytest.ini', 'tox.ini') ? 'pytest' : 'python -m pytest';
    out.lint = 'ruff check .';
  } else if (hasFile(cwd, 'Makefile')) {
    out.lang = 'C/C++ or make-driven';
    out.toolchain.push('make');
    out.build = 'make';
    out.test = 'make test';
    out.dev = 'make run';
  } else if (hasFile(cwd, 'pom.xml', 'build.gradle')) {
    out.lang = 'Java';
    out.toolchain.push('Maven/Gradle');
    out.build = hasFile(cwd, 'pom.xml') ? 'mvn package' : 'gradle build';
    out.test = hasFile(cwd, 'pom.xml') ? 'mvn test' : 'gradle test';
  } else if (hasFile(cwd, 'Gemfile')) {
    out.lang = 'Ruby';
    out.toolchain.push('Ruby');
    out.test = 'bundle exec rspec';
    out.build = 'bundle exec rake build';
  } else if (hasFile(cwd, 'composer.json')) {
    out.lang = 'PHP';
    out.toolchain.push('Composer');
    out.test = 'composer test';
  } else if (hasFile(cwd, '.csproj')) {
    out.lang = 'C#/.NET';
    out.toolchain.push('.NET');
    out.build = 'dotnet build';
    out.test = 'dotnet test';
  }

  // Layout conventions.
  for (const d of ['src', 'lib', 'app', 'tests', 'test', 'spec', 'docs', 'scripts']) {
    if (fs.existsSync(path.join(cwd, d))) out.structure.push(d);
  }
  for (const f of ['eslint.config.js', '.eslintrc', '.prettierrc', 'biome.json', 'tsconfig.json', '.github/workflows']) {
    if (fs.existsSync(path.join(cwd, f))) out.toolchain.push(f.split('/')[0]);
  }

  return out;
}

/** Render an AEGIS.md from a sniff result. */
function buildAegisMd(sniff) {
  const s = sniff;
  const lines = [];
  lines.push(`# AEGIS.md`);
  lines.push('');
  lines.push(`Generated by AEGIS Code /init — edit freely. This file teaches AI agents how to work in this repo.`);
  lines.push('');
  lines.push('## Project');
  lines.push('');
  lines.push(`- Project: ${s.name}`);
  lines.push(`- Language: ${s.lang}`);
  if (s.toolchain.length) lines.push(`- Toolchain: ${[...new Set(s.toolchain)].join(', ')}`);
  lines.push('');
  lines.push('## Commands');
  lines.push('');
  lines.push('Run these to build, test, and lint:');
  lines.push('```bash');
  if (s.build) lines.push(s.build + '      # build');
  if (s.test) lines.push(s.test + '   # test');
  if (s.lint) lines.push(s.lint + '    # lint');
  if (s.dev) lines.push(s.dev + '       # dev server');
  lines.push('```');
  lines.push('');
  if (s.structure.length) {
    lines.push('## Project structure');
    lines.push('');
    for (const d of s.structure) lines.push(`- \`${d}/\` — ${d === 'src' || d === 'lib' ? 'source code' : d === 'tests' || d === 'test' || d === 'spec' ? 'tests' : d}`);
    lines.push('');
  }
  lines.push('## Coding conventions');
  lines.push('');
  lines.push('- Keep changes minimal and focused; match the surrounding style.');
  lines.push('- Before editing a file, read it; verify with the test command above.');
  lines.push('- Prefer the project\'s own scripts over ad-hoc shell commands.');
  lines.push('');
  return lines.join('\n');
}

module.exports = {
  sniffProject,
  buildAegisMd,
  buildClaudeMd: buildAegisMd, // reference name kept for compatibility
};
